"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-09 11:28:54.601955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('related_expedition_ids', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_id'), ['id'], unique=False)
        batch_op.create_index('ix_activities_pub_type', ['published', 'activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_title'), ['title'], unique=False)

    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=False),
    sa.Column('team_leader', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expeditions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expeditions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_expeditions_region'), ['region'], unique=False)

    op.create_table('generated_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_generated_content_id'), ['id'], unique=False)
        batch_op.create_index('ix_generated_content_lookup', ['source_type', 'source_id', 'platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_content_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_content_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_content_source_type'), ['source_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_generated_content_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('variables', sa.Text(), nullable=False),
    sa.Column('units', sa.Text(), nullable=False),
    sa.Column('temporal_coverage', sa.Text(), nullable=False),
    sa.Column('spatial_coverage', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasets_expedition_id'), ['expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_keywords'), ['keywords'], unique=False)
        batch_op.create_index('ix_datasets_pub_exp', ['published', 'expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_title'), ['title'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_expedition_id'), ['expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)
        batch_op.create_index('ix_media_pub_exp', ['published', 'expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_published'), ['published'], unique=False)

    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('journal', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publications_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_publications_expedition_id'), ['expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_id'), ['id'], unique=False)
        batch_op.create_index('ix_publications_pub_exp', ['published', 'expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_publications_year'), ['year'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expedition_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('license', sa.String(length=100), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expedition_id'], ['expeditions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_doi'), ['doi'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_expedition_id'), ['expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_keywords'), ['keywords'], unique=False)
        batch_op.create_index('ix_reports_pub_exp', ['published', 'expedition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_title'))
        batch_op.drop_index(batch_op.f('ix_reports_published'))
        batch_op.drop_index('ix_reports_pub_exp')
        batch_op.drop_index(batch_op.f('ix_reports_keywords'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))
        batch_op.drop_index(batch_op.f('ix_reports_expedition_id'))
        batch_op.drop_index(batch_op.f('ix_reports_doi'))

    op.drop_table('reports')
    with op.batch_alter_table('publications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publications_year'))
        batch_op.drop_index(batch_op.f('ix_publications_title'))
        batch_op.drop_index(batch_op.f('ix_publications_published'))
        batch_op.drop_index('ix_publications_pub_exp')
        batch_op.drop_index(batch_op.f('ix_publications_id'))
        batch_op.drop_index(batch_op.f('ix_publications_expedition_id'))
        batch_op.drop_index(batch_op.f('ix_publications_doi'))

    op.drop_table('publications')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_published'))
        batch_op.drop_index('ix_media_pub_exp')
        batch_op.drop_index(batch_op.f('ix_media_id'))
        batch_op.drop_index(batch_op.f('ix_media_expedition_id'))

    op.drop_table('media')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_title'))
        batch_op.drop_index(batch_op.f('ix_datasets_published'))
        batch_op.drop_index('ix_datasets_pub_exp')
        batch_op.drop_index(batch_op.f('ix_datasets_keywords'))
        batch_op.drop_index(batch_op.f('ix_datasets_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_expedition_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_doi'))

    op.drop_table('datasets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('generated_content', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_generated_content_status'))
        batch_op.drop_index(batch_op.f('ix_generated_content_source_type'))
        batch_op.drop_index(batch_op.f('ix_generated_content_source_id'))
        batch_op.drop_index(batch_op.f('ix_generated_content_platform'))
        batch_op.drop_index('ix_generated_content_lookup')
        batch_op.drop_index(batch_op.f('ix_generated_content_id'))

    op.drop_table('generated_content')
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expeditions_region'))
        batch_op.drop_index(batch_op.f('ix_expeditions_name'))
        batch_op.drop_index(batch_op.f('ix_expeditions_id'))

    op.drop_table('expeditions')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_title'))
        batch_op.drop_index(batch_op.f('ix_activities_published'))
        batch_op.drop_index('ix_activities_pub_type')
        batch_op.drop_index(batch_op.f('ix_activities_id'))

    op.drop_table('activities')
    # ### end Alembic commands ###
